# Generated by Django 3.2.12 on 2022-03-08 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("eveonline", "0015_factions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "review_needed",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_applying_character",
                        to="eveonline.evecharacter",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("approve_application", "Can approve application"),
                    ("reject_application", "Can reject application"),
                    ("review_application", "Can review application"),
                    ("manage_application", "Can override actions on application"),
                    ("view_apis", "Can view applicant APIs"),
                ),
            },
        ),
        migrations.CreateModel(
            name="ApplicationQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=254, verbose_name="Question")),
                ("help_text", models.CharField(blank=True, max_length=254, null=True)),
                ("multi_select", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accept_template_subject",
                    models.TextField(default="", max_length=1000),
                ),
                (
                    "accept_template_body",
                    models.TextField(default="", max_length=10000),
                ),
                (
                    "reject_template_subject",
                    models.TextField(default="", max_length=1000),
                ),
                (
                    "reject_template_body",
                    models.TextField(default="", max_length=10000),
                ),
                (
                    "corp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_corp",
                        to="eveonline.evecorporationinfo",
                    ),
                ),
                (
                    "title",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membertools.ApplicationForm",
                    ),
                ),
                (
                    "manager_groups",
                    models.ManyToManyField(
                        blank=True, related_name="form_manager_groups", to="auth.Group"
                    ),
                ),
                (
                    "questions",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None, to="membertools.ApplicationQuestion"
                    ),
                ),
                (
                    "recruiter_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="form_recruiter_groups",
                        to="auth.Group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="membertools.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_application_comment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_text",
                    models.CharField(max_length=200, verbose_name="Choice"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="membertools.applicationquestion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="membertools.applicationform",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_reviewer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="reviewer_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_reviewer_character",
                to="eveonline.evecharacter",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ApplicationResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="membertools.application",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membertools.applicationquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("question", "application")},
            },
        ),
    ]
