# Generated by Django 4.0.8 on 2023-01-08 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('esi', '0011_add_token_indices'),
        ('membertools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SmallIntegerField(choices=[(1, 'ESI Verified'), (2, 'Previous ESI'), (3, 'Manually Added')])),
                ('linked_on', models.DateTimeField()),
                ('reason', models.TextField(max_length=1024)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='membertools.character')),
                ('esi_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='esi.token')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eveonline.evecharacter')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_links', to='membertools.member')),
            ],
        ),
    ]
