# Generated by Django 4.0.8 on 2023-01-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membertools', '0002_characterlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='decision',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accept'), (2, 'Reject'), (3, 'Withdrawn')], default=0),
        ),
    ]
