# Generated by Django 4.0.10 on 2023-03-23 02:17

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membertools", "0002_titlefilter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="titlefilter",
            options={
                "verbose_name": "Smart Filter: Has Titles",
                "verbose_name_plural": "Smart Filter: Has Titles",
            },
        ),
    ]
