# Generated by Django 4.0.8 on 2023-01-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('membertools', '0003_alter_application_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationaction',
            name='action_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eveonline.evecharacter'),
        ),
        migrations.AlterField(
            model_name='applicationaction',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eveonline.evecharacter'),
        ),
    ]
