# Generated by Django 4.0.10 on 2023-04-19 00:08

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membertools", "0003_alter_titlefilter_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationform",
            name="require_applied",
            field=models.BooleanField(
                default=False, verbose_name="Require Applied Titles"
            ),
        ),
        migrations.AddField(
            model_name="applicationform",
            name="require_awarded",
            field=models.BooleanField(
                default=False, verbose_name="Require Awarded Titles"
            ),
        ),
        migrations.AlterField(
            model_name="applicationform",
            name="allow_applied",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="membertools.applicationtitle",
                verbose_name="Applied Titles",
            ),
        ),
        migrations.AlterField(
            model_name="applicationform",
            name="allow_awarded",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="membertools.applicationtitle",
                verbose_name="Awarded Titles",
            ),
        ),
    ]
