# Generated by Django 4.0.8 on 2023-01-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0015_factions'),
        ('membertools', '0004_alter_applicationaction_action_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_main_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eveonline.evecharacter'),
        ),
        migrations.AddField(
            model_name='member',
            name='main_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_member', to='eveonline.evecharacter'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Under Review'), (3, 'Wait'), (4, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Under Review'), (3, 'Wait'), (4, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='applicationaction',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'Start Review'), (2, 'Accept'), (3, 'Reject'), (4, 'Wait'), (5, 'Release')]),
        ),
    ]
