# Generated by Django 4.0.8 on 2023-01-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membertools', '0005_member_first_main_character_member_main_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='last_status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Under Review'), (3, 'Wait'), (4, 'Processed'), (5, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Under Review'), (3, 'Wait'), (4, 'Processed'), (5, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='applicationaction',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'Start Review'), (2, 'Accept'), (3, 'Reject'), (4, 'Wait'), (5, 'Release'), (6, 'Close')]),
        ),
    ]
