# Generated by Django 4.0.8 on 2023-01-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membertools', '0006_alter_application_last_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterupdatestatus',
            name='last_modified_on',
            field=models.DateTimeField(null=True),
        ),
    ]
