# Generated by Django 4.0.8 on 2023-01-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membertools', '0009_alter_character_alliance_alter_character_faction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationaction',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'Start Review'), (2, 'Accept'), (3, 'Reject'), (4, 'Wait'), (5, 'Release'), (6, 'Close'), (7, 'Withdraw')]),
        ),
    ]
