# Generated by Django 4.0.8 on 2023-01-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0015_factions'),
        ('membertools', '0010_alter_applicationaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='main_character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_member', to='eveonline.evecharacter'),
        ),
    ]
