# Generated by Django 4.0.8 on 2023-01-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0015_factions'),
        ('membertools', '0011_alter_member_main_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_main_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eveonline.evecharacter'),
        ),
    ]
