# Generated by Django 4.0.8 on 2023-01-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membertools', '0012_alter_member_first_main_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='decision',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accept'), (2, 'Reject'), (3, 'Withdraw')], default=0),
        ),
    ]
