# Generated by Django 3.2.16 on 2023-01-22 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membertools', '0013_alter_application_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
